Repository AY2425S1-CS2103T-T14-1/tp, pull requests merged in 2024-11, with the labels that each got.

#147 Update UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#163 Fix cosmetic bugs in UG and improve readability
  docs/UserGuide.md
  src/main/java/seedu/address/Main.java
Labels: alpha-bug

#187 Fix UG links
  docs/UserGuide.md
Labels: alpha-bug

#188 Change keyword for listExpiringPoliciesCommand and modify UG accordingly
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListExpiringPoliciesCommand.java
Labels: alpha-bug

#192 Minor bug fix
  docs/UserGuide.md
Labels: alpha-bug

#197 Fix bugs for EditClaimCommand
  src/main/java/seedu/address/logic/commands/EditClaimCommand.java
  src/main/java/seedu/address/logic/commands/EditPolicyCommand.java
  src/main/java/seedu/address/logic/parser/EditClaimCommandParser.java
  src/test/java/seedu/address/logic/commands/EditClaimCommandTest.java
  src/test/java/seedu/address/logic/parser/EditClaimCommandParserTest.java
Labels: alpha-bug

#190 Fix bugs in ListClaimsCommand
  src/main/java/seedu/address/logic/commands/ListClaimsCommand.java
  src/main/java/seedu/address/logic/parser/ListClaimsCommandParser.java
Labels: alpha-bug

#191 Improve DeleteClaimsCommand and fix minor bugs
  src/main/java/seedu/address/logic/commands/DeleteClaimsCommand.java
  src/main/java/seedu/address/logic/parser/DeleteClaimsCommandParser.java
Labels: alpha-bug

#205 Update ug
  docs/UserGuide.md
Labels: priority.High

#210 Modify ListPoliciesCommand index out of bounds feedback message
  src/main/java/seedu/address/logic/commands/ListPoliciesCommand.java
  src/main/java/seedu/address/logic/parser/ListPoliciesCommandParser.java
Labels: alpha-bug

#224 Modify DG
  docs/DeveloperGuide.md
Labels: priority.Medium

#234 Update Developer Guide and User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindClientCommand.java
  src/test/java/seedu/address/logic/commands/FindClientCommandTest.java
Labels: priority.High, alpha-bug

#334 Bug fixes
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/parser/AddClaimCommandParser.java
  src/test/java/seedu/address/logic/parser/AddClaimCommandParserTest.java
Labels: type.Bug, priority.High

#338 Fix UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/rithiklenin.md
Labels: priority.High

#346 Format UG and address name sensitivity bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug
