Repository AY2425S1-CS2103T-T14-1/tp, pull requests merged in 2024-10, with the labels that each got.

#20 Add Chengke's photo
  docs/images/ckaayy.png
Labels: type.Task

#37 Update Ui.png
  docs/images/Ui.png
Labels: type.Task

#38 Update GitHub badge status on README.md
  README.md
Labels: type.Task

#39 Add Acknowledgment on README.md
  README.md
Labels: type.Task

#10 Update AboutUs.md with yihui's details
  docs/AboutUs.md
  docs/team/yihuididi.md
Labels: type.Task

#14 Update about us
  docs/AboutUs.md
  docs/team/rithiklenin.md
Labels: type.Task

#22 Update AboutUs.md with Chengke's details
  docs/AboutUs.md
Labels: type.Task

#43 Edit Index.md of project website
  docs/_markbind/layouts/default.md
  docs/index.md
  docs/package-lock.json
Labels: type.Task

#49 Update Index.md of project website
  docs/index.md
Labels: type.Task

#48 Update readme
  README.md
Labels: type.Task

#67 Add UpdatePolicyCommand and UpdatePolicyCommandParser
  src/main/java/seedu/address/logic/commands/UpdatePolicyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UpdatePolicyCommandParser.java
  src/test/java/seedu/address/logic/commands/UpdatePolicyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/UpdatePolicyCommandParserTest.java
Labels: type.Task, priority.High

#74 Update FindCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.Task

#76 List expiring policies
  src/main/java/seedu/address/logic/commands/ListExpiringPoliciesCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/policy/EducationPolicy.java
  src/main/java/seedu/address/model/policy/HealthPolicy.java
  src/main/java/seedu/address/model/policy/LifePolicy.java
  src/main/java/seedu/address/model/policy/Policy.java
  src/main/java/seedu/address/model/policy/PolicyExpiryDatePredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedPolicy.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListExpiringPoliciesCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/policy/EducationPolicyTest.java
  src/test/java/seedu/address/model/policy/HealthPolicyTest.java
  src/test/java/seedu/address/model/policy/LifePolicyTest.java
  src/test/java/seedu/address/model/policy/PolicyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPolicyTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#95 Update add policy
  src/main/java/seedu/address/logic/commands/AddPolicyCommand.java
  src/main/java/seedu/address/logic/parser/AddPolicyCommandParser.java
  src/test/java/seedu/address/logic/commands/AddPolicyCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddPolicyCommandParserTest.java
Labels: priority.High

#98 Edit DeletePolicyCommand message
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeletePolicyCommand.java
  src/test/java/seedu/address/logic/commands/DeletePolicyCommandTest.java
Labels: type.Bug

#101 Modify output of ListExpiringPolicies to include insuree name and
  src/main/java/seedu/address/logic/commands/ListExpiringPoliciesCommand.java
  src/test/java/seedu/address/logic/commands/ListExpiringPoliciesCommandTest.java
Labels: type.Task, priority.Medium

#106 Add extension for ListExpiringPolicies to allow for user defined time range
  src/main/java/seedu/address/logic/commands/ListExpiringPoliciesCommand.java
  src/main/java/seedu/address/logic/parser/ListExpiringPoliciesCommandParser.java
  src/main/java/seedu/address/model/policy/PolicyExpiryDatePredicate.java
  src/test/java/seedu/address/logic/commands/ListExpiringPoliciesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListExpiringPoliciesCommandParserTest.java
  src/test/java/seedu/address/model/policy/PolicyExpiryDatePredicateTest.java
Labels: type.Task, priority.Medium

#110 Fix test cases
  src/main/java/seedu/address/logic/commands/ListExpiringPoliciesCommand.java
  src/main/java/seedu/address/model/policy/ExpiryDate.java
  src/test/java/seedu/address/logic/commands/ListExpiringPoliciesCommandTest.java
Labels: type.Bug, priority.High

#114 Edit policy of person
  src/main/java/seedu/address/logic/commands/EditPolicyCommand.java
  src/main/java/seedu/address/logic/commands/UpdatePolicyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditPolicyCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdatePolicyCommandParser.java
  src/main/java/seedu/address/model/policy/EditPolicyDescriptor.java
  src/test/java/seedu/address/logic/commands/EditPolicyCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdatePolicyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditPolicyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UpdatePolicyCommandParserTest.java
  src/test/java/seedu/address/model/policy/EditPolicyDescriptorTest.java
  src/test/java/seedu/address/testutil/EditPolicyDescriptorBuilder.java
Labels: type.Task, priority.High

#118 Fix test case for ListExpiringPolicies
  src/test/java/seedu/address/logic/commands/ListExpiringPoliciesCommandTest.java
Labels: type.Bug

#141 Add ListPoliciesCommand
  src/main/java/seedu/address/logic/commands/ListPoliciesCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListPoliciesCommandParser.java
  src/test/java/seedu/address/logic/commands/ListPoliciesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListPoliciesCommandParserTest.java
Labels: type.Task, priority.High

#144 Add DeleteClaimsCommand
  src/main/java/seedu/address/logic/commands/DeleteClaimsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteClaimsCommandParser.java
  src/main/java/seedu/address/model/policy/Policy.java
  src/test/java/seedu/address/logic/commands/DeleteClaimsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteClaimsCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task, priority.High

#143 Add ListClaimsCommand
  src/main/java/seedu/address/logic/commands/ListClaimsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListClaimsCommandParser.java
  src/test/java/seedu/address/logic/commands/ListClaimsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListClaimsCommandParserTest.java
Labels: type.Task, priority.High
